BestTour3/urls.py
"""
Definition of urls for BestTour3.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'blog$',app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost,name='blogpost'),
    url(r'^newpost$', app.views.newpost,name ='newpost'),
    url(r'^videopost$', app.views.videopost,name ='videopost'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Авторизация',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))
class AnketaForm(forms.Form):
        name = forms.CharField(label = 'Ваше имя', min_length=2, max_length=100)
        city = forms.CharField(label = 'Ваш город', min_length=2, max_length=100)
        job = forms.CharField(label = 'Ваш род занятий',min_length=2,max_length=100)
        gender = forms.ChoiceField(label='Ваш пол',
                                   choices=[('1','Мужской'),('2','Женский')],
                                   widget=forms.RadioSelect,initial=1)
        poezdki = forms.ChoiceField(label='Как часто вы путешествуете',
                                    choices=(('1','Раз в год'),
                                             ('2','2-4 раза в год'),
                                             ('3','4-7 раз в год'),
                                             ('4','Больше 7 раз в год')),initial=1)
        istohnik = forms.ChoiceField(label ='Откуда вы узнали о нашей фирме?',
                                     choices=(('1','Реклама по телевизору'),
                                             ('2','реклама ВК'),
                                            ('3','Реклама по радио')),initial=1)
        notice = forms.BooleanField(label='Получать новости о горящих путевках на e-mail?',
                                    required=False)
        email = forms.EmailField(label='Ваш e-mail', min_length=7)
        message = forms.CharField(label='Пожелания компании:',
                                  widget =forms.Textarea(attrs={'rows':12,'cols':20}))
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text':"Комментарий"}
class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields = ('title','description','content','posted','author','image')
        labels = {'title':"Заголовок",'description':"Краткое описание",'content':"Содержание",'posted':"Дата",'author':"Автор",'image':"Изображение"}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}
{%load staticfiles %}

<h2>{{ title }}.</h2>

<p>Турфирма "BEST-TOUR" предлагает отдых за <br>
    рубежом,в России и странах СНГ по доступным ценам.<br> 
    У нас Вы найдете большой выбор путевок по всем <br>
    направлениям отдыха с вылетом из Санкт-Петербурга, <br>
    Москвы и других городов. Мы предлагаем большой<br>
    выбор экскурсионных и пляжных туров, а также<br>
    активный молодежный отдых и морские круизы.<br>
    Сотрудники нашей компании посетили более 30 стран<br>
    мира и осмотрели сотни отелей и готовы предоставить <br>
    всю необходимую информацию и ответить на все <br>
    возникающие вопросы для того, чтобы отдых оправдал <br>
    Ваши ожидания.<br>
    Приоритетами нашей компании являются:
    <ul>
        <li>гарантия надежности и качества;</li>
        <li>индивидуальный подход к клиентам;</li>
        <li>коммуникабельность и компетентность;</li>
        <li>позитивный настрой.</li>
    </ul>

    <b><em>Отдыхайте с удовольствием!</em></b></p>
<br />
<a><img src="{%static 'app/content/about.jpg'%}" width="800px" </a>


{% endblock %}

app/templates/app/anketa.html
{%extends "app/layout.html"%}
{%block content%}
{% if form != None %}
<br><h2>Ответьте на несколько вопросов: </h2><br />
<div>
    <form method="post">
    {% csrf_token %}
    <label for="{{ form.name.id_for_label}}">{{form.name.label}}:</label>
    {{form.name}}<br><br> 
    <label for="{{ form.city.id_for_label}}">{{form.city.label}}:</label>
    {{form.city}}<br><br>
    <label for="{{ form.job.id_for_label}}">{{form.job.label}}:</label>
    {{form.job}}<br><br>
    <label for="{{ form.gender.id_for_label}}">{{form.gender.label}}:</label>
    {{form.gender}}<br><br>
    <label for="{{ form.poezdki.id_for_label}}">{{form.poezdki.label}}:</label>
    {{form.poezdki}}<br><br>
    <label for="{{ form.istohnik.id_for_label}}">{{form.istohnik.label}}:</label>
    {{form.istohnik}}<br><br>
    <label for="{{ form.notice.id_for_label}}">{{form.notice.label}}:</label>
    {{form.notice}}<br><br>
    <label for="{{ form.email.id_for_label}}">{{form.email.label}}:</label>
    {{form.email}}<br><br>
    <label for="{{ form.message.id_for_label}}">{{form.message.label}}:</label>
    {{form.message}}<br><br>
    <input type="submit" value="Отправить" >
        <script>
                    function field_name()   {
                    $('#id_name').css('background-color','#9eebff');
                    }
                    function field_name2()  {
                    $('#id_name').css('background-color','white');
                    }
                    function field_city()   {
                    $('#id_city').css('background-color','#9eebff');
                    }
                    function field_city2()  {
                    $('#id_city').css('background-color','white');
                    }
                    function field_job()    {
                    $('#id_job').css('background-color','#9eebff');
                    }
                    function field_job2()   {
                    $('#id_job').css('background-color','white');
                    }
                    function field_poezdki()  {
                    $('#id_poezdki').css('background-color', '#9eebff');
                    }
                    function field_poezdki2() {
                    $('#id_poezdki').css('background-color', 'white');
                    }
                    function field_istohnik()  {
                    $('#id_istohnik').css('background-color', '#9eebff');
                    }
                    function field_istohnik2() {
                    $('#id_istohnik').css('background-color', 'white');
                    }
                    function field_notice() {
                    $('#id_notice').css('background-color', '#9eebff');
                    }
                    function field_notice2()    {
                    $('#id_notice').css('background-color', 'white');
                    }
                    function field_email()  {
                    $('#id_email').css('background-color', '#9eebff');
                    }
                    function field_email2() {
                    $('#id_email').css('background-color', 'white');
                    }
                    function field_message()    {
                    $('#id_message').css('background-color','#9eebff');
                    }
                    function field_message2()   {
                    $('#id_message').css('background-color','white');
                    }

        
                    $('#id_name').focus(field_name);
                    $('#id_name').blur(field_name2);
                    $('#id_city').focus(field_city);
                    $('#id_city').blur(field_city2);
                    $('#id_job').focus(field_job);
                    $('#id_job').blur(field_job2);
                    $('#id_poezdki').focus(field_poezdki);
                    $('#id_poezdki').blur(field_poezdki2);
                    $('#id_istohnik').focus(field_istohnik);
                    $('#id_istohnik').blur(field_istohnik2);
                    $('#id_notice').focus(field_notice);
                    $('#id_notice').blur(field_notice2);
                    $('#id_email').focus(field_email);
                    $('#id_email').blur(field_email2);
                    $('#id_message').focus(field_message);
                    $('#id_message').blur(field_message2);
                </script>
    </form>
</div>
{% else %}
 <br><h2>Спасибо,что помогаете стать нам лучше!!</h2>
<h3>Ваши ответы:</h3>
<ul>
    <li><span>Имя:</span>{{data.name}}</li>
    <li><span>Город:</span>{{data.city}}</li>
    <li><span>Пол:</span>{{data.gender}}</li>
    <li><span>Работа:</span>{{data.job}}</li>
    <li><span>Путешествия:</span>{{data.poezdki}}</li>
    <li><span>Вы узнали о нас:</span>{{data.istohnik}}</li>
    <li><span>Получать новости о горящих путевках на e-mail:</span>{{data.notice}}</li>
    <li><span>Ваш e-mail:</span>{{data.email}}</li>
    <li><span>Пожелания компании:</span>{{data.message}}</li>
</ul>
{%endif%}
{%endblock%}

app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{title}}</h2><br />

{% for post in posts %}
<hr/>
<div class="">
<h2> {{post.title}}</h2>
<h4> {{post.posted}}</h4>
<p> {{post.description}}</p>
<p><button class="btn-blog" onclick="document.location='{% url 'blogpost' parametr=post.id %}'">Читать далее</button></p>
</div>

{% endfor %}
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg'%}
     <img src="{{ post_1.image.url}}" alt="Картинка" width="300"/>
{% endif %}
{% autoescape off%}
<p> {{post_1.content|linebreaksbr}} </p>
{% endautoescape %}

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST">{% csrf_token %}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default "> Отправить комментарий </button>
    </div>
    </form>
{% else %}
    <h3>Для добавления своего комментария,пожалуйста,авторизуйтесь</h3>
{% endif %}

{% for comment in comments %}
<hr />
<h7>{{comment.date}}</h7>
<h5>{{comment.author}}</h5>
<p>{{comment.text|linebreaksbr}}</p>
{% endfor %}

<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
   Best Tour<br />
    Россия, город Псков, улица Коммунальная, д. 48<br />
    <abbr title="Телефон"></abbr>
     601-595 ; 999-089;  55-64-61; +7-921- 703-36-99
</address>
<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A8e7aac7ca77e902aa0215b205c905c5f83a53b8a586dddca91a222b984383678&amp;source=constructor" width="607" height="502" frameborder="0"></iframe>

<address>
    <strong>E-mail:</strong>   <a href="mailto:besttour.su@yandex.ru">besttour.su@yandex.ru</a><br />
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

{% load staticfiles %}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="1"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

        <li data-target="#myCarousel" data-slide-to="3"></li>

        <li data-target="#myCarousel" data-slide-to="4"></li>

    </ol>

    <div class="carousel-inner" role="listbox">
         
        <div class="item active">

            <img src="{% static 'app/content/banner0.jpg'%}" width="1200px"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                   Бали — остров государства Индонезия, один из самых удивительных уголков на планете, где встречаются Индийский и Тихий океаны.
                  

                </p>
                <p><a class="btn btn-default" href="https://www.tutu.ru/geo/indonesia/kurort/bali/">

                        Узнать подробнее

                    </a></p>

            </div>

        </div>

        <div class="item ">

            <img src="{% static 'app/content/banner1.jpg'%} "  width="1200px"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                   По распоряжению ФСБ, поручено временно ограничить въезд на территорию страны иностранных граждан с 18 марта по 1 мая 2020 года

                   

                </p>
                <p><a class="btn btn-default" href="https://tass.ru/obschestvo/7996543">

                        Читать далее!

                    </a></p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/banner2.jpg'%}" width=1200px"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    35 лучших виртуальных музеев мира, которые необходимо посетить.
                  

                </p>
                <p><a class="btn btn-default" href="https://www.canva.com/ru_ru/obuchenie/virtualnye-ekskursii/">

                        Узнать подробнее

                    </a></p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/banner3.jpg'%} "  width="1200px"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                     ВИРТУАЛЬНЫЕ ПРОГУЛКИ!!
       

                </p>
                <p><a class="btn btn-default" href="https://www.culture.ru/s/virtualnye-progulki/">

                        Поехали!

                    </a>
                </p>
            </div>

        </div>
     </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>
{%endblock%}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BestTour</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="/static/app/scripts/jquery-1.10.2.js"></script>
    <link rel="shortcut icon" href="{% static '/app/content/favicon.ico' %}" />
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'app/content/logol.jpg' %}" width="150"  /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О компании</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Билеты</a></li>
                    <li><a href="{% url 'anketa' %}">Опрос</a></li>
                 {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                 {% endif %}
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                 {% if  user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                 {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - BESTTOUR</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{%extends "app/layout.html"%}

{%block content%}
{%load staticfiles %}

<h2>{{title}}.</h2>
<br />
<p><a><img src="{%static 'app/content/logo4.png'%}" width="800px" </a></p>
<br />
<div><p><h3>Бронирование авиабилетов онлайн:</h3>
<script charset="utf-8" src="http://www.travelpayouts.com/widgets/51e3fe8f0ba3e2695b000014.js?v=671" type="text/javascript"></script>
</p>
</div>
<br />
<p><a><img src="{%static 'app/content/logo5.jpg'%}" width="400px" </a></p>
<br />
<div><p><h3>Бронирование отелей:</h3>
    <script src="//tp.media/content?promo_id=2693&amp;shmarker=22899&amp;campaign_id=84&amp;locale=ru&amp;border_radius=0&amp;plain=false&amp;powered_by=false" charset="utf-8" type="text/javascript"></script>
 </div>
<br />
<p><a><img src="{%static 'app/content/logo6.png'%}" width="800px" </a></p>
<br />
<div><p><h3>Бронирование Ж/Д билетов:</h3>
    <script src="https://c45.travelpayouts.com/content?promo_id=1655&shmarker=22899&locale=ru&border_radius=0px&full_width=true&logo=false&tborder=false&hide_header=false&powered_by=false" charset="utf-8" async="true"></script>
 </div>
{%endblock%}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте существующий аккаунт для входа.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Вход" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста,введите верное имя пользователя или пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}
{% block scripts %}
{% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>
{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет, {{ user.username }}?</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выход</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data"> {% csrf_token %} 
<div>
    {{blogform.as_p}}
    <button type="submit" class="save btn btn-default">Сохранить статью</button>
</div>
</form>
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация пользователя</h2>
    <form method="POST" > {% csrf_token %}
        <div>
            {{ regform.as_p}}
            <button type="submit" class="save btn btn-default">
                Зарегистрировать
            </button>
        </div>
    </form>
{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<div>
    <h1>Пляж</h1>
    <video src="/media/video1.mp4" controls="controls" width="500" poster="/media/poster2.jpg" ></video>
</div>
<hr />
<div>
    <h1>Закат</h1>
    <video src="/media/video2.mp4" controls="controls" width="500" poster="/media/poster1.jpg" ></video>
</div>
{% endblock %}